//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.Rattz
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOption
    {
        public int Id { get; set; }
        public int OptionsCount { get; set; }
        public System.DateTime DateAwarded { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
